name: deploy

on:
  push:
    tags: ['*']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: run tests
        run: make full-pipeline
      - name: publish package
        run: |
          pip install setuptools
          pip install twine
          python setup.py sdist
          TWINE_PASSWORD=${{ secrets.TWINE_PASSWORD }} TWINE_USERNAME=${{ secrets.TWINE_USER }} twine upload --non-interactive dist/*
